export const USER_ACTION_TYPE = {
  CHECK_USER_SEACTION: "user/CHECK_USER_SEACTION",
  GOOGLE_SIGNIN_START: "user/GOOGLE_SIGNIN_START",
  MAIL_SIGNIN_START: "user/MAIL_SIGNIN_START",
  SIGNIN_SUCCESS: "user/SIGNIN_SUCCESS",
  SIGNIN_FAILTED: "user/SIGNIN_FAILTED",
  SIGNUP_START: "user/SIGNUP_START",
  SIGNUP_SUCCESS: "user/SIGNUP_SUCCESS",
  SIGNUP_FAILTED: "user/SIGNUP_FAILTED",
  SIGNOUT_START: "user/SIGNOUT_START",
  SIGNOUT_SUCCESS: "user/SIGNOUT_SUCCESS",
  SIGNOUT_FAILTED: "user/SIGNOUT_FAILTED",
};
