export const USER_ACTION_TYPE = {
  CHECK_USER_SEACTION: "user/CHECK_USER_SEACTION",
  GOOGLE_SIGNIN_START: "user/GOOGLE_SIGNIN_START",
  MAIL_SIGNIN_START: "user/MAIL_SIGNIN_START",
  SIGNIN_SUCCESS: "user/SIGNIN_SUCCESS",
  SIGNIN_FAILTED: "user/SIGNIN_FAILTED",
  SIGNUP_START: "user/SIGNUP_START",
};
